// packages/vue/src/components/SignaturePad.vue
<template>
  <div class="signature-pad-container" :class="{ 'signature-pad-disabled': !enabled }">
    <canvas ref="canvasRef" class="signature-pad-canvas" :width="width" :height="height" :style="canvasStyle"></canvas>

    <div v-if="showControls" class="signature-pad-controls">
      <button v-if="showClearButton" class="signature-pad-btn signature-pad-btn-clear" :disabled="isEmpty"
        @click="handleClear">
        {{ clearButtonText }}
      </button>

      <button v-if="showUndoButton" class="signature-pad-btn signature-pad-btn-undo" :disabled="!canUndo"
        @click="handleUndo">
        {{ undoButtonText }}
      </button>

      <button v-if="showRedoButton" class="signature-pad-btn signature-pad-btn-redo" :disabled="!canRedo"
        @click="handleRedo">
        {{ redoButtonText }}
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch, onMounted } from 'vue';
import { SignatureConfig } from '@ldesign/signature-core';
import { useSignature } from '../composables/useSignature';

// Props
interface Props {
  width?: number;
  height?: number;
  penColor?: string;
  minWidth?: number;
  maxWidth?: number;
  enabled?: boolean;
  showControls?: boolean;
  showClearButton?: boolean;
  showUndoButton?: boolean;
  showRedoButton?: boolean;
  clearButtonText?: string;
  undoButtonText?: string;
  redoButtonText?: string;
  config?: Partial<SignatureConfig>;
}

const props = withDefaults(defineProps<Props>(), {
  width: 400,
  height: 200,
  penColor: '#000000',
  minWidth: 0.5,
  maxWidth: 2.5,
  enabled: true,
  showControls: true,
  showClearButton: true,
  showUndoButton: true,
  showRedoButton: true,
  clearButtonText: '清空',
  undoButtonText: '撤销',
  redoButtonText: '重做',
});

// Emits
const emit = defineEmits<{
  begin: [event: PointerEvent];
  change: [event: PointerEvent];
  end: [event: PointerEvent];
  clear: [];
  undo: [];
  redo: [];
}>();

// Create config from props
const signatureConfig = computed<SignatureConfig>(() => ({
  width: props.width,
  height: props.height,
  penColor: props.penColor,
  minWidth: props.minWidth,
  maxWidth: props.maxWidth,
  ...props.config,
  onBegin: (e: PointerEvent) => emit('begin', e),
  onChange: (e: PointerEvent) => emit('change', e),
  onEnd: (e: PointerEvent) => emit('end', e),
}));

// Use signature composable
const {
  canvasRef,
  instance,
  isEmpty,
  canUndo,
  canRedo,
  clear,
  undo,
  redo,
  toDataURL,
  toSVG,
  toJSON,
  fromJSON,
  download,
  setEnabled,
} = useSignature(signatureConfig);

// Canvas style
const canvasStyle = computed(() => ({
  border: '1px solid #ddd',
  borderRadius: '4px',
  cursor: props.enabled ? 'crosshair' : 'not-allowed',
}));

// Handle actions
const handleClear = () => {
  clear();
  emit('clear');
};

const handleUndo = () => {
  undo();
  emit('undo');
};

const handleRedo = () => {
  redo();
  emit('redo');
};

// Watch enabled prop
watch(() => props.enabled, (value) => {
  setEnabled(value);
});

// Expose methods to parent
defineExpose({
  clear,
  undo,
  redo,
  toDataURL,
  toSVG,
  toJSON,
  fromJSON,
  download,
  isEmpty: () => isEmpty.value,
  canUndo: () => canUndo.value,
  canRedo: () => canRedo.value,
  getInstance: () => instance.value,
});
</script>

<style scoped>
.signature-pad-container {
  display: inline-block;
  position: relative;
}

.signature-pad-disabled {
  opacity: 0.6;
  pointer-events: none;
}

.signature-pad-canvas {
  display: block;
  background: #fff;
}

.signature-pad-controls {
  margin-top: 8px;
  display: flex;
  gap: 8px;
}

.signature-pad-btn {
  padding: 6px 16px;
  font-size: 14px;
  border: 1px solid #ddd;
  border-radius: 4px;
  background: #fff;
  cursor: pointer;
  transition: all 0.2s;
}

.signature-pad-btn:hover:not(:disabled) {
  border-color: #409eff;
  color: #409eff;
}

.signature-pad-btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.signature-pad-btn-clear:hover:not(:disabled) {
  border-color: #f56c6c;
  color: #f56c6c;
}
</style>

// packages/lit/src/components/signature-pad.ts
/**
 * Lit Web Component for Signature Pad
 */

import { LitElement, html, css, PropertyValues } from 'lit';
import { customElement, property, query, state } from 'lit/decorators.js';
import { SignaturePad as SignaturePadCore, createSignaturePad } from '@ldesign/signature-core';
import type { SignatureConfig, SignatureData, ExportFormat } from '@ldesign/signature-core';
import { SmoothAlgorithm } from '@ldesign/signature-core';

@customElement('signature-pad')
export class SignaturePadElement extends LitElement {
  // Properties
  @property({ type: Number }) width = 600;
  @property({ type: Number }) height = 300;
  @property({ type: String, attribute: 'pen-color' }) penColor = '#000000';
  @property({ type: Number, attribute: 'min-width' }) minWidth = 0.5;
  @property({ type: Number, attribute: 'max-width' }) maxWidth = 2.5;
  @property({ type: String, attribute: 'smooth-algorithm' }) smoothAlgorithm: SmoothAlgorithm = SmoothAlgorithm.CATMULL_ROM;
  @property({ type: Boolean, attribute: 'pressure-sensitive' }) pressureSensitive = true;
  @property({ type: Boolean }) enabled = true;
  @property({ type: Boolean, attribute: 'show-controls' }) showControls = true;
  @property({ type: Boolean, attribute: 'show-clear-button' }) showClearButton = true;
  @property({ type: Boolean, attribute: 'show-undo-button' }) showUndoButton = true;
  @property({ type: Boolean, attribute: 'show-redo-button' }) showRedoButton = true;
  @property({ type: String, attribute: 'clear-button-text' }) clearButtonText = '清空';
  @property({ type: String, attribute: 'undo-button-text' }) undoButtonText = '撤销';
  @property({ type: String, attribute: 'redo-button-text' }) redoButtonText = '重做';

  // State
  @state() private isEmpty = true;
  @state() private canUndo = false;
  @state() private canRedo = false;

  // Elements
  @query('canvas') private canvas!: HTMLCanvasElement;

  // Instance
  private instance: SignaturePadCore | null = null;

  static styles = css`
    :host {
      display: inline-block;
    }
    
    .container {
      display: inline-block;
      position: relative;
    }
    
    .container.disabled {
      opacity: 0.6;
      pointer-events: none;
    }
    
    canvas {
      display: block;
      border: 1px solid #ddd;
      border-radius: 4px;
      background: white;
    }
    
    .controls {
      margin-top: 8px;
      display: flex;
      gap: 8px;
    }
    
    button {
      padding: 6px 16px;
      font-size: 14px;
      border: 1px solid #ddd;
      border-radius: 4px;
      background: white;
      cursor: pointer;
      transition: all 0.2s;
      font-family: inherit;
    }
    
    button:hover:not(:disabled) {
      border-color: #409eff;
      color: #409eff;
    }
    
    button:disabled {
      opacity: 0.5;
      cursor: not-allowed;
    }
    
    .btn-clear:hover:not(:disabled) {
      border-color: #f56c6c;
      color: #f56c6c;
    }
  `;

  protected firstUpdated(): void {
    this.initializeSignaturePad();
  }

  protected updated(changedProperties: PropertyValues): void {
    if (changedProperties.has('enabled')) {
      this.instance?.setEnabled(this.enabled);
    }

    // Update config if properties changed
    if (this.instance && (
      changedProperties.has('penColor') ||
      changedProperties.has('minWidth') ||
      changedProperties.has('maxWidth') ||
      changedProperties.has('smoothAlgorithm') ||
      changedProperties.has('pressureSensitive')
    )) {
      this.instance.updateConfig(this.getConfig());
    }
  }

  disconnectedCallback(): void {
    super.disconnectedCallback();
    this.instance?.destroy();
    this.instance = null;
  }

  private initializeSignaturePad(): void {
    if (!this.canvas) return;

    const config = this.getConfig();
    this.instance = createSignaturePad(this.canvas, config);
    this.updateState();
  }

  private getConfig(): SignatureConfig {
    return {
      width: this.width,
      height: this.height,
      penColor: this.penColor,
      minWidth: this.minWidth,
      maxWidth: this.maxWidth,
      smoothAlgorithm: this.smoothAlgorithm,
      pressureSensitive: this.pressureSensitive,
      onBegin: (e: PointerEvent) => this.dispatchEvent(new CustomEvent('begin', { detail: e })),
      onChange: (e: PointerEvent) => {
        this.updateState();
        this.dispatchEvent(new CustomEvent('change', { detail: e }));
      },
      onEnd: (e: PointerEvent) => {
        this.updateState();
        this.dispatchEvent(new CustomEvent('end', { detail: e }));
      },
    };
  }

  private updateState(): void {
    if (!this.instance) return;

    this.isEmpty = this.instance.isEmpty();
    this.canUndo = this.instance.canUndo();
    this.canRedo = this.instance.canRedo();
  }

  // Public methods
  public clear(): void {
    this.instance?.clear();
    this.updateState();
    this.dispatchEvent(new CustomEvent('clear'));
  }

  public undo(): void {
    this.instance?.undo();
    this.updateState();
    this.dispatchEvent(new CustomEvent('undo'));
  }

  public redo(): void {
    this.instance?.redo();
    this.updateState();
    this.dispatchEvent(new CustomEvent('redo'));
  }

  public toDataURL(format?: 'png' | 'jpeg', quality?: number): string {
    return this.instance?.toDataURL(format, quality) || '';
  }

  public toSVG(): string {
    return this.instance?.toSVG() || '';
  }

  public toJSON(): SignatureData | null {
    return this.instance?.toJSON() || null;
  }

  public fromJSON(data: SignatureData): void {
    this.instance?.fromJSON(data);
    this.updateState();
  }

  public download(fileName?: string, format?: ExportFormat, quality?: number): void {
    this.instance?.download(fileName, format, quality);
  }

  public getInstance(): SignaturePadCore | null {
    return this.instance;
  }

  protected render() {
    return html`
      <div class="container ${!this.enabled ? 'disabled' : ''}">
        <canvas width="${this.width}" height="${this.height}"></canvas>
        
        ${this.showControls ? html`
          <div class="controls">
            ${this.showClearButton ? html`
              <button
                class="btn-clear"
                ?disabled="${this.isEmpty}"
                @click="${this.clear}"
              >
                ${this.clearButtonText}
              </button>
            ` : ''}
            
            ${this.showUndoButton ? html`
              <button
                class="btn-undo"
                ?disabled="${!this.canUndo}"
                @click="${this.undo}"
              >
                ${this.undoButtonText}
              </button>
            ` : ''}
            
            ${this.showRedoButton ? html`
              <button
                class="btn-redo"
                ?disabled="${!this.canRedo}"
                @click="${this.redo}"
              >
                ${this.redoButtonText}
              </button>
            ` : ''}
          </div>
        ` : ''}
      </div>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'signature-pad': SignaturePadElement;
  }
}
