// packages/vue/src/components/SignaturePad.vue
<template>
  <div class="signature-pad-container" :class="{ 'signature-pad-disabled': !enabled }">
    <canvas ref="canvasRef" class="signature-pad-canvas" :width="width" :height="height" :style="canvasStyle"></canvas>

    <div v-if="showControls" class="signature-pad-controls">
      <button v-if="showClearButton" class="signature-pad-btn signature-pad-btn-clear" :disabled="isEmpty"
        @click="handleClear">
        {{ clearButtonText }}
      </button>

      <button v-if="showUndoButton" class="signature-pad-btn signature-pad-btn-undo" :disabled="!canUndo"
        @click="handleUndo">
        {{ undoButtonText }}
      </button>

      <button v-if="showRedoButton" class="signature-pad-btn signature-pad-btn-redo" :disabled="!canRedo"
        @click="handleRedo">
        {{ redoButtonText }}
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch, onMounted } from 'vue';
import { SignatureConfig } from '@ldesign/signature-core';
import { useSignature } from '../composables/useSignature';

// Props
interface Props {
  width?: number;
  height?: number;
  penColor?: string;
  minWidth?: number;
  maxWidth?: number;
  enabled?: boolean;
  showControls?: boolean;
  showClearButton?: boolean;
  showUndoButton?: boolean;
  showRedoButton?: boolean;
  clearButtonText?: string;
  undoButtonText?: string;
  redoButtonText?: string;
  config?: Partial<SignatureConfig>;
}

const props = withDefaults(defineProps<Props>(), {
  width: 400,
  height: 200,
  penColor: '#000000',
  minWidth: 0.5,
  maxWidth: 2.5,
  enabled: true,
  showControls: true,
  showClearButton: true,
  showUndoButton: true,
  showRedoButton: true,
  clearButtonText: '清空',
  undoButtonText: '撤销',
  redoButtonText: '重做',
});

// Emits
const emit = defineEmits<{
  begin: [event: PointerEvent];
  change: [event: PointerEvent];
  end: [event: PointerEvent];
  clear: [];
  undo: [];
  redo: [];
}>();

// Create config from props
const signatureConfig = computed<SignatureConfig>(() => ({
  width: props.width,
  height: props.height,
  penColor: props.penColor,
  minWidth: props.minWidth,
  maxWidth: props.maxWidth,
  ...props.config,
  onBegin: (e: PointerEvent) => emit('begin', e),
  onChange: (e: PointerEvent) => emit('change', e),
  onEnd: (e: PointerEvent) => emit('end', e),
}));

// Use signature composable
const {
  canvasRef,
  instance,
  isEmpty,
  canUndo,
  canRedo,
  clear,
  undo,
  redo,
  toDataURL,
  toSVG,
  toJSON,
  fromJSON,
  download,
  setEnabled,
} = useSignature(signatureConfig);

// Canvas style
const canvasStyle = computed(() => ({
  border: '1px solid #ddd',
  borderRadius: '4px',
  cursor: props.enabled ? 'crosshair' : 'not-allowed',
}));

// Handle actions
const handleClear = () => {
  clear();
  emit('clear');
};

const handleUndo = () => {
  undo();
  emit('undo');
};

const handleRedo = () => {
  redo();
  emit('redo');
};

// Watch enabled prop
watch(() => props.enabled, (value) => {
  setEnabled(value);
});

// Expose methods to parent
defineExpose({
  clear,
  undo,
  redo,
  toDataURL,
  toSVG,
  toJSON,
  fromJSON,
  download,
  isEmpty: () => isEmpty.value,
  canUndo: () => canUndo.value,
  canRedo: () => canRedo.value,
  getInstance: () => instance.value,
});
</script>

<style scoped>
.signature-pad-container {
  display: inline-block;
  position: relative;
}

.signature-pad-disabled {
  opacity: 0.6;
  pointer-events: none;
}

.signature-pad-canvas {
  display: block;
  background: #fff;
}

.signature-pad-controls {
  margin-top: 8px;
  display: flex;
  gap: 8px;
}

.signature-pad-btn {
  padding: 6px 16px;
  font-size: 14px;
  border: 1px solid #ddd;
  border-radius: 4px;
  background: #fff;
  cursor: pointer;
  transition: all 0.2s;
}

.signature-pad-btn:hover:not(:disabled) {
  border-color: #409eff;
  color: #409eff;
}

.signature-pad-btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.signature-pad-btn-clear:hover:not(:disabled) {
  border-color: #f56c6c;
  color: #f56c6c;
}
</style>

// packages/react/src/components/SignaturePad.tsx
/**
 * React Signature Pad component
 */

import React, { useEffect, useImperativeHandle, forwardRef, CSSProperties } from 'react';
import type { SignatureConfig, SignatureData, ExportFormat } from '@ldesign/signature-core';
import { useSignature } from '../hooks/useSignature';

export interface SignaturePadProps {
  width?: number;
  height?: number;
  penColor?: string;
  minWidth?: number;
  maxWidth?: number;
  enabled?: boolean;
  showControls?: boolean;
  showClearButton?: boolean;
  showUndoButton?: boolean;
  showRedoButton?: boolean;
  clearButtonText?: string;
  undoButtonText?: string;
  redoButtonText?: string;
  className?: string;
  style?: CSSProperties;
  canvasStyle?: CSSProperties;
  config?: Partial<SignatureConfig>;
  onBegin?: (event: PointerEvent) => void;
  onChange?: (event: PointerEvent) => void;
  onEnd?: (event: PointerEvent) => void;
  onClear?: () => void;
  onUndo?: () => void;
  onRedo?: () => void;
}

export interface SignaturePadRef {
  clear: () => void;
  undo: () => void;
  redo: () => void;
  toDataURL: (format?: 'png' | 'jpeg', quality?: number) => string;
  toSVG: () => string;
  toJSON: () => SignatureData | null;
  fromJSON: (data: SignatureData) => void;
  download: (fileName?: string, format?: ExportFormat, quality?: number) => void;
  isEmpty: () => boolean;
  canUndo: () => boolean;
  canRedo: () => boolean;
}

/**
 * Signature Pad Component
 */
export const SignaturePad = forwardRef<SignaturePadRef, SignaturePadProps>((props, ref) => {
  const {
    width = 400,
    height = 200,
    penColor = '#000000',
    minWidth = 0.5,
    maxWidth = 2.5,
    enabled = true,
    showControls = true,
    showClearButton = true,
    showUndoButton = true,
    showRedoButton = true,
    clearButtonText = '清空',
    undoButtonText = '撤销',
    redoButtonText = '重做',
    className = '',
    style,
    canvasStyle,
    config,
    onBegin,
    onChange,
    onEnd,
    onClear,
    onUndo,
    onRedo,
  } = props;

  // Create config
  const signatureConfig: SignatureConfig = {
    width,
    height,
    penColor,
    minWidth,
    maxWidth,
    ...config,
    onBegin,
    onChange,
    onEnd,
  };

  // Use signature hook
  const {
    canvasRef,
    isEmpty: isEmptyState,
    canUndo: canUndoState,
    canRedo: canRedoState,
    clear,
    undo,
    redo,
    toDataURL,
    toSVG,
    toJSON,
    fromJSON,
    download,
    setEnabled,
  } = useSignature(signatureConfig);

  // Handle actions
  const handleClear = () => {
    clear();
    onClear?.();
  };

  const handleUndo = () => {
    undo();
    onUndo?.();
  };

  const handleRedo = () => {
    redo();
    onRedo?.();
  };

  // Watch enabled prop
  useEffect(() => {
    setEnabled(enabled);
  }, [enabled, setEnabled]);

  // Expose methods via ref
  useImperativeHandle(ref, () => ({
    clear,
    undo,
    redo,
    toDataURL,
    toSVG,
    toJSON,
    fromJSON,
    download,
    isEmpty: () => isEmptyState,
    canUndo: () => canUndoState,
    canRedo: () => canRedoState,
  }));

  const containerClass = `signature-pad-container ${!enabled ? 'signature-pad-disabled' : ''} ${className}`;

  const defaultCanvasStyle: CSSProperties = {
    border: '1px solid #ddd',
    borderRadius: '4px',
    cursor: enabled ? 'crosshair' : 'not-allowed',
    background: '#fff',
    display: 'block',
    ...canvasStyle,
  };

  return (
    <div className={containerClass} style={style}>
      <canvas
        ref={canvasRef}
        className="signature-pad-canvas"
        width={width}
        height={height}
        style={defaultCanvasStyle}
      />

      {showControls && (
        <div className="signature-pad-controls" style={controlsStyle}>
          {showClearButton && (
            <button
              className="signature-pad-btn signature-pad-btn-clear"
              disabled={isEmptyState}
              onClick={handleClear}
              style={buttonStyle}
            >
              {clearButtonText}
            </button>
          )}

          {showUndoButton && (
            <button
              className="signature-pad-btn signature-pad-btn-undo"
              disabled={!canUndoState}
              onClick={handleUndo}
              style={buttonStyle}
            >
              {undoButtonText}
            </button>
          )}

          {showRedoButton && (
            <button
              className="signature-pad-btn signature-pad-btn-redo"
              disabled={!canRedoState}
              onClick={handleRedo}
              style={buttonStyle}
            >
              {redoButtonText}
            </button>
          )}
        </div>
      )}
    </div>
  );
});

SignaturePad.displayName = 'SignaturePad';

// Default styles
const controlsStyle: CSSProperties = {
  marginTop: '8px',
  display: 'flex',
  gap: '8px',
};

const buttonStyle: CSSProperties = {
  padding: '6px 16px',
  fontSize: '14px',
  border: '1px solid #ddd',
  borderRadius: '4px',
  background: '#fff',
  cursor: 'pointer',
  transition: 'all 0.2s',
};

export default SignaturePad;
